### ISSUE TITLE
Lighthouse html in artifacts

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/gimbal#98]
We should include lighthouse.html in artifacts so engineers can look at it when CI fails.

**Comment by mitchellsimoens** [comment]
The issue with executing lighthouse programmatically is the outputs are different than when you execute via the cli. If you change the `output` setting that defaults to `json` to be `html` so that the report generated is the HTML but we wouldn't be able to parse it because it's not JSON anymore.

We may be able to get down to the `ReportGenerator` class to turn the lhr into html: https://github.com/GoogleChrome/lighthouse/blob/81a8a5cb3d5e785494fe8549cbe747de2325c17c/lighthouse-core/report/report-generator.js#L35

**Comment by grgur** [comment]
@mitchellsimoens you can output both `json` and `html` from lighthouse by providing both switches. Am I missing the point?

**Comment by mitchellsimoens** [comment]
We aren’t executing it via cli and of course setting the property twice in an object doesn’t work the same, unless it supports an array of strings but the docs say it uses the same property in the response.

**Comment by grgur** [comment]
Based on Lighthouse [type def](https://github.com/GoogleChrome/lighthouse/blob/888bd6dc9d927a734a8e20ea8a0248baa5b425ed/typings/externs.d.ts#L82-L119) it looks like `output` can take an array. @mitchellsimoens do you think that could be the solution?

**Comment by mitchellsimoens** [comment]
Per https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#differences-from-cli-flags, it says this for `outputPath`:

> Ignored, output is returned as string in .report property.

Also, lighthouse typings are very unfinished (per them too) so an input vs output difference wouldn't be surprising at all either. No use keep talking until someone actually tries it.

**Comment by mitchellsimoens** [comment]
#103
